[package]
name = "tsot"
version = "0.1.0"
edition = "2021"

[features]
default = ["sync", "imc", "async"]
sync = []
imc = []
async = []
redis = []


[dependencies]
async-trait = "0.1.83"
thiserror = "1.0.65"
tokio = { version = "1.41.0", features = ["rt"] }

dashmap = "6.1.0"
fred = "9.3.0"
